name: CI Pipeline for Multi-Module Gradle Project

on:
  push:
    branches:
      - master  # Trigger the pipeline for pushes to the 'master' branch
  pull_request:
    branches:
      - master  # Trigger the pipeline for pull requests targeting 'master'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Cache Gradle dependencies to speed up subsequent builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Run Gradle build (clean and build)
      - name: Build with Gradle
        run: ./gradlew clean build
