name: CI Pipeline for Multi-Module Gradle Project

on:
  push:
    branches:
      - master  # Trigger the pipeline for pushes to the 'main' branch
  pull_request:
    branches:
      - master  # Trigger the pipeline for pull requests targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup java and gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          java-package: jdk
          distribution: 'temurin'  # You can change to 'zulu', 'oracle', etc.
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v2

      # Step3: Run build and test (includes creating the distribution ZIP)
      - name: Build with Gradle
        run: ./gradlew clean build

      # Step : Unzip the SonarQube distribution file
      - name: Unzip SonarQube distribution
        run: |
          mkdir -p sonar-application
          unzip sonar-application/build/distributions/sonar-*.zip -d sonar-application

      # Step 5: Start SonarQube server based on the OS
      - name: Start SonarQube server (Linux)
        run: |
          chmod +x sonar-application/sonar*/
          sonar-application/sonar*/bin/linux-x86-64/sonar.sh start

