name: CI Pipeline for Multi-Module Gradle Project

on:
  push:
    branches:
      - master  # Trigger the pipeline for pushes to the 'main' branch
  pull_request:
    branches:
      - master  # Trigger the pipeline for pull requests targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK (Java 11 in this case, adjust to your version)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Cache Gradle dependencies to speed up subsequent builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Install Gradle (if you want to ensure the specific version)
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      # Run Gradle build (and tests)
      - name: Build and test with Gradle
        run: ./gradlew clean build

