name: CI Pipeline for Multi-Module Gradle Project

on:
  push:
    branches:
      - master  # Trigger the pipeline for pushes to the 'main' branch
  pull_request:
    branches:
      - master  # Trigger the pipeline for pull requests targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          java-package: jdk
          distribution: 'temurin'  # You can change to 'zulu', 'oracle', etc.
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success
          token: ${{ secrets.GITHUB_TOKEN }}

      # Set up Gradle (ensure the wrapper is used)
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v2

      # Run Gradle build (and tests)
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Test with Gradle
        run: ./gradlew test

